# Bag file
bag_topic_01: "/stereo_camera/left/image_raw"
bag_topic_02: "/odometry/filtered"

# Preprocessing
image_filter: "clahe" # gauss clahe none
plot_test: "no" # no yes
plot_test_cnn: "no"

# Local View topic 
topic_local_view: '/husky_hwu/LocalView/Template'

# Tempory Memory - value="apical / distal"
tempory_memory: "distal"

# Cortical Grid Cells
PC_DIM_XY: 11
PC_DIM_TH: 18
POSECELL_VTRANS_SCALING: 1./5.
ODO_ROT_SCALING: 1.0

# Visual Cells
VT_START: 2
VT_MATCH_THRESHOLD: 0.75
VT_GLOBAL_DECAY: 0.1
VT_ACTIVE_DECAY: 1.0